#
# Here Application
#

version: '3'
services:
  redis:
    image: "shellboot/redis"
    volumes:
      - /var/here/redis:/var/redis
    restart: always
  mysql:
    image: "shellboot/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /var/here/mysql:/var/mysql
      - ./docs/docker/mysql/conf:/usr/local/mysql/etc/conf.d
    restart: always
  php:
    image: "shellboot/php:phalcon"
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    restart: always
  nginx:
    image: "shellboot/nginx"
    depends_on:
     - php
    volumes:
      - .:/var/www
      - ./docs/conf/nginx/vhost:/usr/local/nginx/conf/vhost
      - ./docs/conf/nginx/extra:/usr/local/nginx/conf/extra
    ports:
      - "80:80"
      - "443:443"
    restart: always
