#
# Here Application
#

version: '3'
services:
  php:
    image: "shellboot/php"
    volumes:
      - .:/var/www
  nginx:
    image: "shellboot/nginx"
    depends_on:
     - php
    volumes:
      - .:/var/www
      - ./Config/docker/nginx/conf:/usr/local/nginx/etc
    ports:
      - "80:80"
