# blogger application

version: '3'
services:
  php:
    image: "shellboot/php"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=here
    volumes:
      - .:/var/www
  nginx:
    image: "shellboot/nginx"
    depends_on:
     - php
    volumes:
      - .:/var/www
      - ./Config/docker/nginx/conf:/usr/local/nginx/etc
    ports:
      - "80:80"
