%YAML: 1.2

# databases configures
databases:
  -
    host: localhost
    port: 3306
    username: root
    password: root
    database: here
    charset: utf8
    provider: mysql


# caches server configures
caches:
  -
    host: localhost
    port: 11211
    provider: redis
