#
# Blogger Configure File
#
# True: yes|on|true
# False: no|off|false
#


# user environments
environment:
  debug_mode: off
  strict_router: off
  auto_commit: on


# router configure
router:
  dashboard: dashboard


# databases configures
database:
  -
    host: mysql
    port: 3306
    username: root
    password: root
    database: here
    charset: utf8
    driver: mysql


# caches server configures
cache:
  -
    name: master
    host: redis
    port: 6379
    driver: redis
