#
# Blogger Configure File
#
# True: yes|on|true
# False: no|off|false
#


# user environments
environments:
  debug_mode: off
  strict_router: off


# router configure
router:
  dashboard: dashboard


# databases configures
databases:
  -
    host: mysql
    port: 3306
    username: root
    password: root
    database: here
    charset: utf8
    driver: mysql


# caches server configures
caches:
  -
    host: redis
    port: 11211
    driver: redis
