#
# Here Blogger Configure File
#


# databases configures
databases:
  -
    host: mysql
    port: 3306
    username: root
    password: root
    database: here
    charset: utf8
    driver: mysql


# caches server configures
caches:
  -
    host: redis
    port: 11211
    driver: redis
